### ISSUE TITLE
Getting Unable to decode stream: java.io.FileNotFoundException if crop is false

### ISSUE THREAD

**Issue by ASKabanets** [Drjacky/ImagePicker#25]
Hi! Thanks for the library!

Checked sample app.
Getting `BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /document/image:197117: open failed: ENOENT (No such file or directory)` if don't add `crop()`

```           
ImagePicker.with(this)
//                .crop()
//                .cropOval()
                .maxResultSize(512, 512, true)
                .createIntentFromDialog { profileLauncher.launch(it) }
```

**Comment by Drjacky** [comment]
@ASKabanets What library version you use and which Android API you tests on?
I've used [v2.1.8](https://github.com/Drjacky/ImagePicker/releases/tag/2.1.8) on API 29 and API 30 and it works.

**Comment by ASKabanets** [comment]
I've just downloaded this sample project, launched it on my OnePlus 5 (Android 10) and tried to get image from gallery or camera. It works great, but when crop is false I got FileNotFoundException.
Then I've created empty project (empty screen just with one button) and added ImagePicker as a dependency. Used the same piece of code as in the sample project - same: when crop is false it throws exception

**Comment by Drjacky** [comment]
Could you attach your sample project here?

**Comment by ASKabanets** [comment]
[https://drive.google.com/file/d/1TO5VLXkkVM_bUwk9qBR9co2Zk4ml8V3O/view?usp=sharing](url)

**Comment by Drjacky** [comment]
@ASKabanets You're right. The error is in logcat but, the app works and you could easily use the `uri` and pass it to your Image Loader library.

I'll fix that false-positive exception. Thanks!

**Comment by ASKabanets** [comment]
It works (when crop is false) if you use `uri` to set an image. If you use file path it doesn't work ( `ImagePicker.getFilePath(activityResult.data)` )

**Comment by Drjacky** [comment]
@ASKabanets Please use Uri. I'm gonna update the sample app and the Readme.

**Comment by GuilhE** [comment]
I've having the same problem with this setup:

```
ImagePicker
     .with(activity)
     .maxResultSize(maxWidth, maxHeight, true)
     .createIntentFromDialog { intentLauncher.invoke(it) }
```
I can have a path:
```
private val imageLauncher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
       if (it.resultCode == Activity.RESULT_OK) {
           uploadImage(ImagePicker.getFilePath(it.data)!!)
       } else {...}
}
```
But:

> java.io.FileNotFoundException: /external_files/Android/data/com.myapp/files/DCIM/Camera/IMG_20210917_130950299.jpg: open failed: ENOENT (No such file or directory)

**Comment by GuilhE** [comment]
This is the path I get using my version: `/data/user/0/com.myapp/files/temp.JPEG` 🤔

**Comment by Drjacky** [comment]
@GuilhE Using file path (`ImagePicker.getFilePath(activityResult.data)`) when the crop is false doesn't work (I'll fix it later) but, using `uri` works perfectly even if the crop is off:
->
`val uri = it.data?.data!!`

**Comment by GuilhE** [comment]
I've used that, but I get exactly the same path 🤔

**Comment by Drjacky** [comment]
@GuilhE No, not `.path`.
This:
```kotlin
private val galleryLauncher =
        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
            if (it.resultCode == Activity.RESULT_OK) {
                val uri = it.data?.data!!
                mGalleryUri = uri
                imgGallery.setLocalImage(uri)
            } else parseError(it)
        }
```

**Comment by GuilhE** [comment]
What's the `imgGallery.setLocalImage(uri)`? Ideally I've taken a photo and I want the path to upload it as `MultipartFormData`

**Comment by GuilhE** [comment]
I've [changed](https://github.com/GuilhE/ImagePicker/commit/de00824ab665b041238a9d5b81a6a8b00c1422ee) my GalleryProvider to include your permissions logic, but maintaining all my previous logic. It's working now 👍🏼

**Comment by ClarkXP** [comment]
I'm getting same issue when try to open camera without crop() option.
Can be recreated removing crop option in pickCameraImage() function.

`Unable to decode stream: java.io.FileNotFoundException: /external_files/Android/data/com.github.drjacky.imagepicker.sample/files/DCIM/Camera/IMG_20230109_103418027.jpg: open failed: ENOENT (No such file or directory)
`
`java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                                    	at com.github.drjacky.imagepicker.provider.CompressionProvider.compressTask(CompressionProvider.kt:72)
                                                                                                    	at com.github.drjacky.imagepicker.provider.CompressionProvider.access$compressTask(CompressionProvider.kt:24)
                                                                                                    	at com.github.drjacky.imagepicker.provider.CompressionProvider$compress$1.invokeSuspend(CompressionProvider.kt:58)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at com.github.drjacky.imagepicker.provider.CompressionProvider.compress(CompressionProvider.kt:57)
                                                                                                    	at com.github.drjacky.imagepicker.ImagePickerActivity.setImage(ImagePickerActivity.kt:172)
                                                                                                    	at com.github.drjacky.imagepicker.provider.CameraProvider.handleResult(CameraProvider.kt:142)
                                                                                                    	at com.github.drjacky.imagepicker.ImagePickerActivity.cameraLauncher$lambda$1(ImagePickerActivity.kt:59)
                                                                                                    	at com.github.drjacky.imagepicker.ImagePickerActivity.$r8$lambda$TbnVizF4DKsKWrDO5-zrgXMal9g(Unknown Source:0)
                                                                                                    	at com.github.drjacky.imagepicker.ImagePickerActivity$$ExternalSyntheticLambda1.onActivityResult(Unknown Source:4)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:149)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
                                                                                                    	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
                                                                                                    	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
                                                                                                    	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1428)
                                                                                                    	at android.app.Activity.performStart(Activity.java:8254)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3789)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8337)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)`

**Comment by Drjacky** [comment]
@ClarkXP Please create a new issue with the all necessary information
