### ISSUE TITLE
ImagePickerActivity does not launch

### ISSUE THREAD

**Issue by HosseinKurd** [Drjacky/ImagePicker#32]
I just tried as Readme notes
but **createIntentFromDialog** and **createIntent** not worked
and ImagePickerActivity not launched

**Comment by Drjacky** [comment]
@HosseinKurd Would you please run the sample app and let me know if you have the issue again?

**Comment by voghDev** [comment]
Hi man! 

This code just worked in my Xiaomi Mi A3 plus my Nexus 5X emulator:
```
    private val pickImageLauncher =
        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
           // ...
        }

        pickImageLauncher.launch(
            ImagePicker.with(requireActivity())
                .createIntent()
        )
```
I hope it can be helpful for you too!

**Comment by Husseinhj** [comment]
I have the same problem.

Snippet code:
``` kotlin
private val startForProfileImageResult =
        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result: ActivityResult ->
        
        }
....

ImagePicker.with(this)
                .provider(ImageProvider.BOTH)
                .createIntentFromDialog { intent ->
                    startForProfileImageResult.launch(intent)
                }
```


here is my crash log:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fast.dic.dict, PID: 27624
    java.lang.RuntimeException: Unable to start activity ComponentInfo{fast.dic.dict/com.github.drjacky.imagepicker.ImagePickerActivity}: java.lang.NullPointerException: null cannot be cast to non-null type android.graphics.Bitmap.CompressFormat
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3450)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3602)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
     Caused by: java.lang.NullPointerException: null cannot be cast to non-null type android.graphics.Bitmap.CompressFormat
        at com.github.drjacky.imagepicker.provider.CropProvider.<init>(CropProvider.kt:63)
        at com.github.drjacky.imagepicker.ImagePickerActivity.loadBundle(ImagePickerActivity.kt:101)
        at com.github.drjacky.imagepicker.ImagePickerActivity.onCreate(ImagePickerActivity.kt:74)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
```
