### ISSUE TITLE
 Canvas: trying to draw too large(256576512bytes) bitmap.

### ISSUE THREAD

**Issue by fatemi2020** [Drjacky/ImagePicker#42]
**Describe the bug**
 Canvas: trying to draw too large(256576512bytes) bitmap.

**To Reproduce**
1. Go to 'Take photo from camera'
2. set image mode as 64MP (or above if support)
3. Skip crop if enabled and Press "Done"
4. App will crash and See error in Logcat

**Smartphone (please complete the following information):**
 - Device: Samsung A71
 - OS: Android
 - Version 11

**Logcat stack trace**
    java.lang.RuntimeException: Canvas: trying to draw too large(256576512bytes) bitmap.
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:281)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:91)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
        at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:109)
        at android.widget.ImageView.onDraw(ImageView.java:1453)
        at android.view.View.draw(View.java:23901)
        at android.view.View.updateDisplayListIfDirty(View.java:22776)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.draw(View.java:23904)
        at android.view.View.updateDisplayListIfDirty(View.java:22776)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.draw(View.java:23904)
        at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
        at android.view.View.updateDisplayListIfDirty(View.java:22776)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.draw(View.java:23904)
        at android.widget.ScrollView.draw(ScrollView.java:2876)
        at android.view.View.updateDisplayListIfDirty(View.java:22776)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.draw(View.java:23904)
        at android.view.View.updateDisplayListIfDirty(View.java:22776)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.java:268)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.java:256)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
2021-10-20 15:54:36.684 28776-28776/? E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.draw(View.java:23904)
        at android.view.View.updateDisplayListIfDirty(View.java:22776)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.draw(View.java:23904)
        at com.android.internal.policy.DecorView.draw(DecorView.java:1282)
        at android.view.View.updateDisplayListIfDirty(View.java:22776)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:579)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:585)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:662)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4994)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4701)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3818)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2575)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9910)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:744)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by fatemi2020** [comment]
this link helped me to resolve issue.
The Picasso needs these tow functions:
`.resize(2048, 1600)`
`.onlyScaleDown() // the image will only be resized if it's bigger than 2048x 1600 pixels.`
