### ISSUE TITLE
Add Intent Flags

### ISSUE THREAD

**Issue by Kisty** [Drjacky/ImagePicker#9]
Thanks for this library. Have you any idea how to allow the returned `Uri` as a persistable URI? I think it requires putting a flag in the startActivity `Intent` but I see no way to add flags.

```
requireActivity().grantUriPermission(
    requireActivity().packageName,
    fileUri,
    data.flags and
            Intent.FLAG_GRANT_READ_URI_PERMISSION and
            Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION
)
requireActivity().contentResolver.takePersistableUriPermission(
    fileUri,
    data.flags and
            Intent.FLAG_GRANT_READ_URI_PERMISSION
)
```

Log:
```
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=530587092, result=-1, data=Intent { dat=file:///storage/emulated/0/DCIM/Camera/IMG_20210323_162851252.jpg (has extras) }} to activity {uk.co.imagitech.completetheorytestkit/uk.co.imagitech.learn2.passguarantee.PassGuaranteeClaimActivity}: java.lang.SecurityException: No persistable permission grants found for UID 10161 and Uri file:///storage/emulated/0/DCIM/Camera/IMG_20210323_162851252.jpg
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.SecurityException: No persistable permission grants found for UID 10161 and Uri file:///storage/emulated/0/DCIM/Camera/IMG_20210323_162851252.jpg
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.IUriGrantsManager$Stub$Proxy.takePersistableUriPermission(IUriGrantsManager.java:280)
        at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:2851)
        at uk.co.imagitech.learn2.passguarantee.ui.PassGuaranteeClaimFragment$onActivityCreated$1$1.invoke(PassGuaranteeClaimFragment.kt:58)
        at uk.co.imagitech.learn2.passguarantee.ui.PassGuaranteeClaimFragment$onActivityCreated$1$1.invoke(PassGuaranteeClaimFragment.kt:22)
        at com.github.drjacky.imagepicker.ImagePicker$Builder$startActivity$1.invoke(ImagePicker.kt:359)
        at com.github.drjacky.imagepicker.ImagePicker$Builder$startActivity$1.invoke(ImagePicker.kt:92)
        at com.github.florent37.inlineactivityresult.kotlin.Kotlin_activity_resultKt$sam$com_github_florent37_inlineactivityresult_callbacks_SuccessCallback$0.onSuccess(Unknown Source:2)
        at com.github.florent37.inlineactivityresult.InlineActivityResult.onReceivedActivityResult(InlineActivityResult.java:113)
        at com.github.florent37.inlineactivityresult.InlineActivityResult.access$000(InlineActivityResult.java:29)
        at com.github.florent37.inlineactivityresult.InlineActivityResult$1.onActivityResult(InlineActivityResult.java:45)
        at com.github.florent37.inlineactivityresult.ActivityResultFragment.onActivityResult(ActivityResultFragment.java:69)
        at androidx.fragment.app.FragmentManager$9.onActivityResult(FragmentManager.java:2889)
        at androidx.fragment.app.FragmentManager$9.onActivityResult(FragmentManager.java:2869)
        at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:344)
        at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:308)
        at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:618)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
        at android.app.Activity.dispatchActivityResult(Activity.java:8310)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by Drjacky** [comment]
May I know what do you want to do?

It's already here:
https://github.com/Drjacky/ImagePicker/blob/f1bde377e30506e6c2e6613efc0327b6f1c909b4/imagepicker/src/main/kotlin/com/github/drjacky/imagepicker/util/IntentUtils.kt#L37-L44

**Comment by Drjacky** [comment]
Please try the latest version.
